language: php

os: linux
dist: xenial

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '8.0'

branches:
    only:
        - master

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

git:
    submodules: false

notifications:
    email: samuel.breu@bresam.ch
