version: '3.5'

services:
    php:
        build: docker/php
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: client_host=${XDEBUG_HOST} client_port=${XDEBUG_PORT} idekey=${XDEBUG_IDEKEY}
            PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
        volumes:
            - ~/.composer:/var/www/.composer
            - .:/var/www/html
